[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "http://localhost:8899"

[programs.localnet]
vulnerable_unsafe_arithmetic = "VuLnUnSaFeArItHmEtIc11111111111111111111111"
secure_unsafe_arithmetic = "SeCuReUnSaFeArItHmEtIc1111111111111111111"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
