[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "http://localhost:8899"

[programs.localnet]
vulnerable_pda_derivation = "VuLnPdAdErIvAtIoN11111111111111111111111111"
secure_pda_derivation = "SeCuRePdAdErIvAtIoN1111111111111111111111"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
