[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "http://localhost:8899"

[programs.localnet]
vulnerable_cpi_reentrancy = "DW5PRzSRWd1oAS8mDiV915GNh1hvpWrs7dxehpdnkD6b"
secure_cpi_reentrancy = "DmLeYUrsmp4D8PPFYzqoeoVxicmHcDNoFUt3KbJGtQ8K"
attacker_cpi_reentrancy = "BY2ntBPnsu3LhtA92jHYWUR4RTCm85tC3bNRyZT9Vsu9"
pinocchio_vulnerable_cpi_reentrancy = "ANpcyVKyc3Vz2U9aPwjLzsHvwzzuimiG5DThsPz6Qgsa"
pinocchio_secure_cpi_reentrancy = "Du8vRGWEyC5bjXDnjVNHK3JZdHUhmJqu4bbt4tWwrPQD"
pinocchio_attacker_cpi_reentrancy = "Czak4jHPLpBDrWLjkfPMRaUgYnyVWUuiMsWn3vbqyujM"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
