[package]
name = "pinocchio-vulnerable-unsafe-arithmetic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = { version = "0.10", features = ["alloc"] }
solana-program-log = "1.1"

[features]
no-entrypoint = []
